#ifndef MUSE_SIMULATOR_SIMULATOR_HOST_EVENT_QUEUE_HPP
#define MUSE_SIMULATOR_SIMULATOR_HOST_EVENT_QUEUE_HPP
#include "host.hpp"

namespace muse::simulator {

}
#endif //MUSE_SIMULATOR_SIMULATOR_HOST_EVENT_QUEUE_HPP
